app:
  name: apprun
  version: "1.0.0"

database:
  driver: postgres
  host: localhost
  port: 5432
  user: apprun
  password: "dev_password_123"
  dbname: apprun_dev

poc:
  enabled: true
  database: "postgres://user:pass@localhost:5432/apprun_poc"
  apikey: "poc-api-key-123456"